---
- hosts: all
  vars:
    - os_packages:
        - git
  tasks:
    - name: "Upload .ssh config"
      template:
        src: "templates/ssh_config"
        dest: "~/.ssh/config"
        mode: 0600
    - name: "Update AWS config"
      file: dest=~/.aws state=directory
    - template:
        src: "templates/aws_config"
        dest: "~/.aws/config"
    - name: "install common dependencies"
      yum: name={{item}}
      with_items: "{{os_packages}}"
      become: yes
    - name: "synchronize repository"
      git:
        repo: https://github.com/sebastiankosz/wpc_album_web.git
        dest: ~/album_web
        accept_hostkey: true

- hosts: webui
  vars:
    - python_packages:
        - Flask
        - boto3
  tasks:
    - name: "install python dependencies"
      pip: name={{item}}
      with_items: "{{python_packages}}"
      become: yes
    - name: "synchronize repository"
      git:
        repo: https://github.com/sebastiankosz/wpc_album_web.git
        dest: ~/album_web
        accept_hostkey: true

- hosts: pdf
  vars:
    - os_packages:
        - gcc
        - libjpeg-devel
        - zlib-devel
    - python_packages:
        - jinja2
        - xhtml2pdf
  tasks:
    - name: "install common dependencies"
      yum: name={{item}}
      with_items: "{{os_packages}}"
      become: yes
    - name: "install python dependencies"
      pip: name={{item}}
      with_items: "{{python_packages}}"
      become: yes
    - name: "synchronize repository"
      git:
        repo: https://github.com/sebastiankosz/wpc_album_pdfgen.git
        dest: ~/album_pdfgen
        accept_hostkey: true